---
title: "Lab 3 Report"
author: "Logan Hillers"
date: "`r format(Sys.Date())`"
output: github_document
---

Instructions for this lab report can be found on [Your assignment section of Lab Assignment 3 Introduction to ggplot2](https://biol275-msum.github.io/introduction-to-ggplot2.html#your-assignment) on the lab website.

## Fireflies

> A. Insert an R code chunk and create a graph depicting the frequency distribution of the 35 mass measurements. It should have legible text and appropriate axis labels.

ggplot(data = firefly_mass) +
  
  geom_histogram(mapping = aes(x = spermatophoreMass), binwidth = 0.01,
                 boundary = 0, closed = "left", 
                 fill = "#C5351B", color = "black") +
  
  labs(x = "Spermatophore Mass", y = "Frequency (number of fireflies)") +
  
  scale_y_continuous(breaks = seq(0, 30, 5), limits = c(0, 12), 
                     expand = expansion(mult = 0)) +
  
  scale_x_continuous(breaks = seq(0, 600, 100)) +
  
  theme_classic() +
  theme(
    axis.title = element_text(face = "bold"),
    axis.text = element_text(color = "black", size = rel(1))
  )

> B. What type of graph did you choose in part (A)? Why?

I chose a histogram for part (A) because I wanted to visualize the frequency of that each spermatophore mass occured in the sample.

> C. Describe the shape of the frequency distribution. What are its main features?

The shape of the frequency distribution appears to have two main peaks, making it bimodal.

> D. What term would be used to describe the largest measurement in the frequency distribution? You can refer to the lecture slides, your notes, or the textbook.

The mode is the largest measurement in the frequency distribution.

## Bird orders

I read the data using the code provided by the instructor. The dataset is from the auk package and was originally named ebird_taxonomy. I converted it to a tibble, removed non-species taxa, and named the new dataset birds.


> E. How many bird species are in the new birds dataset? How did you find out?

There are 10,721 bird species in the new bird dataset, which I found by loading the data in my console by running the code below and counting how many rows there were.

birds

> H. How many orders are there? You can get this right by counting on the graph, but you will only get full points if you use some code to figure it out.

I counted how many orders there were by running the code below and once again counting each row. In total, there were 41 orders.

distinct(birds, order)

> F. Insert an R code chunk and create a graph depicting the distribution of orders in the birds dataset. Sort the orders with the most frequent on the left. It should have legible text and appropriate axis labels.

ggplot(data = birds) +
  
  geom_bar(mapping = aes(x = fct_infreq(order)), fill = "#C5351B", 
           width = .8) +
  
  labs(x = "Order", y = "Frequency (number of species)") +
  
  scale_y_continuous(limits = c(0, 6500), expand = expansion(mult = 0)) +
  
  theme_classic(base_size = 12) +
  
  theme(
    axis.title = element_text(face = "bold"),
    axis.text = element_text(color = "black", size = rel(1)),
    axis.text.x = element_text(angle = 45, hjust = 1),
    axis.ticks.x = element_blank()
  )

> G. What kind of graph did you create? Why?

I created a bar grph because I was comparing the number of species in each order, nothing to do with frequency.

## Links to peer review

I reviewed Faith's lab report at this URL: \_\_\_

Faith reviewed my lab report at this URL: \_\_\_

## Session Info

Here is my session information:

```{r}
sessioninfo::session_info()
```
